import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { z } from "zod";
import { itemPriorities, itemStatuses, itemTypes, type RealEstateLabItem, type RealEstateLabItemInput, type RealEstateLabItemUpdateInput, type RealEstateLabItemResult } from "../contracts";

type Db = Record<string, any>;
const noHtml = z.string().nullable().transform((v) => v?.trim() || null).refine((v) => !v || !/[<>]/.test(v), "Não use HTML bruto.");
const schema = z.object({ itemType: z.enum(itemTypes), title: z.string().trim().min(1), description: noHtml.optional(), status: z.enum(itemStatuses), priority: z.enum(itemPriorities).nullable().optional(), responsibleUserId: z.string().uuid().nullable().optional(), dueAt: z.string().trim().nullable().optional(), occurredAt: z.string().trim().nullable().optional(), resultNotes: z.string().trim().nullable().optional() });
const updateSchema = schema.partial();
const rowToItem = (r: Db): RealEstateLabItem => ({ id:r.id, accountId:r.account_id, itemType:r.item_type, title:r.title, description:r.description, status:r.status, priority:r.priority, responsibleUserId:r.responsible_user_id, dueAt:r.due_at, occurredAt:r.occurred_at, resultNotes:r.result_notes, createdBy:r.created_by, updatedBy:r.updated_by, createdAt:r.created_at, updatedAt:r.updated_at });
async function uid(supabase: SupabaseClient) { const { data } = await supabase.auth.getUser(); if (!data.user?.id) throw new Error("unauthenticated"); return data.user.id; }
const payload = (v: Partial<RealEstateLabItemInput>, userId: string) => ({ item_type:v.itemType, title:v.title, description:v.description ?? null, status:v.status, priority:v.priority ?? null, responsible_user_id:v.responsibleUserId ?? null, due_at:v.dueAt ?? null, occurred_at:v.occurredAt ?? null, result_notes:v.resultNotes ?? null, updated_by:userId });
export const realEstateLabItemAdapter = {
  async list(supabase: SupabaseClient, input: { accountId: string; itemType?: string | null; status?: string | null }) { let q = supabase.from("real_estate_lab_items").select("*").eq("account_id", input.accountId).order("created_at", { ascending:false }); if (input.itemType) q = q.eq("item_type", input.itemType); if (input.status) q = q.eq("status", input.status); const { data, error } = await q; if (error) throw error; return (data ?? []).map(rowToItem); },
  async getById(supabase: SupabaseClient, accountId: string, id: string) { const { data, error } = await supabase.from("real_estate_lab_items").select("*").eq("account_id", accountId).eq("id", id).maybeSingle(); if (error) throw error; return data ? rowToItem(data) : null; },
  async create(supabase: SupabaseClient, accountId: string, input: RealEstateLabItemInput): Promise<RealEstateLabItemResult> { try { const userId = await uid(supabase); const v = schema.parse(input); const { data, error } = await supabase.from("real_estate_lab_items").insert({ ...payload(v, userId), account_id: accountId, created_by: userId }).select("*").single(); if (error) throw error; return { ok:true, data: rowToItem(data) }; } catch(e){ return { ok:false, error:e instanceof Error ? e.message : "Erro ao salvar item." }; } },
  async update(supabase: SupabaseClient, accountId: string, id: string, input: RealEstateLabItemUpdateInput): Promise<RealEstateLabItemResult> { try { const userId = await uid(supabase); const v = updateSchema.parse(input); const { data, error } = await supabase.from("real_estate_lab_items").update(payload(v, userId)).eq("account_id", accountId).eq("id", id).select("*").single(); if (error) throw error; return { ok:true, data: rowToItem(data) }; } catch(e){ return { ok:false, error:e instanceof Error ? e.message : "Erro ao atualizar item." }; } },
  async changeStatus(supabase: SupabaseClient, accountId: string, id: string, status: string) { return this.update(supabase, accountId, id, { status: z.enum(itemStatuses).parse(status) }); },
  async delete(supabase: SupabaseClient, accountId: string, id: string) { const { error } = await supabase.from("real_estate_lab_items").delete().eq("account_id", accountId).eq("id", id); return error ? { ok:false, error:error.message } : { ok:true as const }; },
};
