import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { z } from "zod";
import { contentChannels, contentStatuses, type RealEstateLabContent, type RealEstateLabContentInput, type RealEstateLabContentUpdateInput, type RealEstateLabContentResult } from "../contracts";

type Db = Record<string, any>;
const noHtml = z.string().nullable().transform((v) => v?.trim() || null).refine((v) => !v || !/[<>]/.test(v), "Não use HTML bruto.");
const schema = z.object({ title: z.string().trim().min(1), topic: z.string().trim().min(1), channel: z.enum(contentChannels), format: z.string().trim().nullable().optional(), hook: z.string().trim().nullable().optional(), body: noHtml.optional(), cta: z.string().trim().nullable().optional(), status: z.enum(contentStatuses), scheduledFor: z.string().trim().nullable().optional(), publishedAt: z.string().trim().nullable().optional(), resultNotes: z.string().trim().nullable().optional(), learningNotes: z.string().trim().nullable().optional() });
const updateSchema = schema.partial();
const rowToContent = (r: Db): RealEstateLabContent => ({ id:r.id, accountId:r.account_id, title:r.title, topic:r.topic, channel:r.channel, format:r.format, hook:r.hook, body:r.body, cta:r.cta, status:r.status, scheduledFor:r.scheduled_for, publishedAt:r.published_at, resultNotes:r.result_notes, learningNotes:r.learning_notes, createdBy:r.created_by, updatedBy:r.updated_by, createdAt:r.created_at, updatedAt:r.updated_at });
async function uid(supabase: SupabaseClient) { const { data } = await supabase.auth.getUser(); if (!data.user?.id) throw new Error("unauthenticated"); return data.user.id; }
const payload = (v: Partial<RealEstateLabContentInput>, userId: string) => ({ title:v.title, topic:v.topic, channel:v.channel, format:v.format ?? null, hook:v.hook ?? null, body:v.body ?? null, cta:v.cta ?? null, status:v.status, scheduled_for:v.scheduledFor ?? null, published_at:v.publishedAt ?? null, result_notes:v.resultNotes ?? null, learning_notes:v.learningNotes ?? null, updated_by:userId });
export const realEstateLabContentAdapter = {
  async list(supabase: SupabaseClient, input: { accountId: string; status?: string | null; channel?: string | null }) { let q = supabase.from("real_estate_lab_contents").select("*").eq("account_id", input.accountId).order("created_at", { ascending:false }); if (input.status) q = q.eq("status", input.status); if (input.channel) q = q.eq("channel", input.channel); const { data, error } = await q; if (error) throw error; return (data ?? []).map(rowToContent); },
  async getById(supabase: SupabaseClient, accountId: string, id: string) { const { data, error } = await supabase.from("real_estate_lab_contents").select("*").eq("account_id", accountId).eq("id", id).maybeSingle(); if (error) throw error; return data ? rowToContent(data) : null; },
  async create(supabase: SupabaseClient, accountId: string, input: RealEstateLabContentInput): Promise<RealEstateLabContentResult> { try { const userId = await uid(supabase); const v = schema.parse(input); const { data, error } = await supabase.from("real_estate_lab_contents").insert({ ...payload(v, userId), account_id: accountId, created_by: userId }).select("*").single(); if (error) throw error; return { ok:true, data: rowToContent(data) }; } catch(e){ return { ok:false, error:e instanceof Error ? e.message : "Erro ao salvar conteúdo." }; } },
  async update(supabase: SupabaseClient, accountId: string, id: string, input: RealEstateLabContentUpdateInput): Promise<RealEstateLabContentResult> { try { const userId = await uid(supabase); const v = updateSchema.parse(input); const { data, error } = await supabase.from("real_estate_lab_contents").update(payload(v, userId)).eq("account_id", accountId).eq("id", id).select("*").single(); if (error) throw error; return { ok:true, data: rowToContent(data) }; } catch(e){ return { ok:false, error:e instanceof Error ? e.message : "Erro ao atualizar conteúdo." }; } },
  async changeStatus(supabase: SupabaseClient, accountId: string, id: string, status: string) { return this.update(supabase, accountId, id, { status: z.enum(contentStatuses).parse(status) }); },
  async delete(supabase: SupabaseClient, accountId: string, id: string) { const { error } = await supabase.from("real_estate_lab_contents").delete().eq("account_id", accountId).eq("id", id); return error ? { ok:false, error:error.message } : { ok:true as const }; },
};
