"use client";
import { useActionState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { FeedbackMessage } from "@/components/ui/feedback-message";
import { contentChannels, contentStatuses, type RealEstateLabContent } from "@/lib/real-estate-lab";
import type { LabActionState } from "../actions";
export function ContentForm({ account, action, content }: { account: string; action: (account:string, prev:LabActionState, fd:FormData)=>Promise<LabActionState>; content?: RealEstateLabContent }) { const bound = action.bind(null, account); const [state, formAction] = useActionState(bound, {}); return <form action={formAction} className="space-y-3 rounded-xl border bg-white p-4 shadow-sm"><h3 className="font-semibold">{content ? "Editar conteúdo" : "Criar conteúdo"}</h3>{state.error && <FeedbackMessage tone="error">{state.error}</FeedbackMessage>}{state.message && <FeedbackMessage tone="success">{state.message}</FeedbackMessage>}{content && <input type="hidden" name="id" value={content.id}/>}<Input name="title" placeholder="Título" defaultValue={content?.title} required/><Input name="topic" placeholder="Assunto editorial" defaultValue={content?.topic} required/><div className="grid gap-2 md:grid-cols-2"><select name="channel" defaultValue={content?.channel ?? "instagram"} className="rounded border p-2">{contentChannels.map(s=><option key={s}>{s}</option>)}</select><select name="status" defaultValue={content?.status ?? "idea"} className="rounded border p-2">{contentStatuses.map(s=><option key={s}>{s}</option>)}</select></div><Input name="format" placeholder="Formato" defaultValue={content?.format ?? ""}/><Textarea name="hook" placeholder="Hook" defaultValue={content?.hook ?? ""}/><Textarea name="body" placeholder="Corpo (sem HTML)" defaultValue={content?.body ?? ""}/><Input name="cta" placeholder="CTA" defaultValue={content?.cta ?? ""}/><div className="grid gap-2 md:grid-cols-2"><Input name="scheduledFor" type="datetime-local"/><Input name="publishedAt" type="datetime-local"/></div><Textarea name="resultNotes" placeholder="Notas de resultado" defaultValue={content?.resultNotes ?? ""}/><Textarea name="learningNotes" placeholder="Aprendizados" defaultValue={content?.learningNotes ?? ""}/><Button type="submit">Salvar conteúdo</Button></form> }
