from pathlib import Path
p=Path('docs/lp-planejamento.md')
s=p.read_text()
s=s.replace('Criar `12.4 — Validação e liberação administrativa de landing pages por taxon`', 'Criar `12.4 — Autorização, validação e liberação administrativa de landing pages por taxon`')
s=s.replace('retirar o catálogo anterior de `landing_page` como contrato vigente e registrar que seu novo catálogo será definido em `18.5`', 'retirar o conjunto anterior de módulos e variantes de `landing_page` como contrato vigente e registrar que o novo conjunto será definido em `18.5`')
s=s.replace('responsável pelo catálogo inicial, funções estruturais, campos, cardinalidades, variantes, especializações excepcionais sobre a raiz', 'responsável pelo conjunto inicial de módulos e variantes, suas funções estruturais, campos, cardinalidades e especializações excepcionais sobre a raiz')
s=s.replace('`18.5.3 — Catálogo e função dos módulos`', '`18.5.3 — Módulos e funções estruturais`')
s=s.replace('Permitir identificação das contas de teste para que seus eventos não contaminem métricas comerciais reais quando tracking e relatórios forem implementados.', 'Identificar as LPs e os eventos produzidos sob autorização específica de teste, permitindo separá-los dos indicadores comerciais reais sem classificar a conta como conta de teste.')
s=s.replace('identificar contas de teste para que seus eventos possam ser separados dos indicadores comerciais reais.', 'identificar as LPs e os eventos produzidos sob autorização específica de teste, permitindo separá-los dos indicadores comerciais reais sem classificar a conta como conta de teste.')
p.write_text(s)
