"use server";
import "server-only";
import { revalidatePath } from "next/cache";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getAccessContext } from "@/lib/access/getAccessContext";
import { realEstateLabContentAdapter, realEstateLabItemAdapter } from "@/lib/real-estate-lab";

export type LabActionState = { ok?: boolean; message?: string; error?: string };
const uuidRe = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function enabledAccountId() { const id = process.env.REAL_ESTATE_LAB_ACCOUNT_ID?.trim(); return id && uuidRe.test(id) ? id : null; }
async function gate(account: string, write: boolean, del = false) { const allowed = enabledAccountId(); if (!allowed) notFound(); const ctx = await getAccessContext({ params:{ account }, route:`/a/${account}/labs/imobiliario` }); if (!ctx || ctx.blocked || ctx.account?.id !== allowed) notFound(); const role = ctx.member?.role; if (write && !(["owner","admin","editor"].includes(role ?? ""))) throw new Error("Sem permissão para gravar."); if (del && !(["owner","admin"].includes(role ?? ""))) throw new Error("Sem permissão para excluir."); return ctx.account.id; }
const val = (fd: FormData, k: string) => fd.get(k)?.toString() || null;
const empty = (s: string | null) => s && s.trim() ? s.trim() : null;
function path(account:string){ return `/a/${account}/labs/imobiliario`; }
export async function saveContentAction(account: string, _prev: LabActionState, fd: FormData): Promise<LabActionState> { try { const accountId = await gate(account, true); const supabase = await createClient(); const id = val(fd,"id"); const input = { title: val(fd,"title") ?? "", topic: val(fd,"topic") ?? "", channel: val(fd,"channel") as any, format: empty(val(fd,"format")), hook: empty(val(fd,"hook")), body: empty(val(fd,"body")), cta: empty(val(fd,"cta")), status: val(fd,"status") as any, scheduledFor: empty(val(fd,"scheduledFor")), publishedAt: empty(val(fd,"publishedAt")), resultNotes: empty(val(fd,"resultNotes")), learningNotes: empty(val(fd,"learningNotes")) }; const r = id ? await realEstateLabContentAdapter.update(supabase, accountId, id, input) : await realEstateLabContentAdapter.create(supabase, accountId, input); revalidatePath(path(account)); return r.ok ? { ok:true, message:"Conteúdo salvo." } : { ok:false, error:r.error }; } catch(e){ return { ok:false, error:e instanceof Error ? e.message : "Erro ao salvar conteúdo."}; } }
export async function setContentStatusAction(account: string, fd: FormData) { const accountId = await gate(account, true); const supabase = await createClient(); await realEstateLabContentAdapter.changeStatus(supabase, accountId, val(fd,"id") ?? "", val(fd,"status") ?? ""); revalidatePath(path(account)); }
export async function deleteContentAction(account: string, fd: FormData) { const accountId = await gate(account, true, true); const supabase = await createClient(); await realEstateLabContentAdapter.delete(supabase, accountId, val(fd,"id") ?? ""); revalidatePath(path(account)); }
export async function saveItemAction(account: string, _prev: LabActionState, fd: FormData): Promise<LabActionState> { try { const accountId = await gate(account, true); const supabase = await createClient(); const id = val(fd,"id"); const input = { itemType: val(fd,"itemType") as any, title: val(fd,"title") ?? "", description: empty(val(fd,"description")), status: val(fd,"status") as any, priority: empty(val(fd,"priority")) as any, responsibleUserId: empty(val(fd,"responsibleUserId")), dueAt: empty(val(fd,"dueAt")), occurredAt: empty(val(fd,"occurredAt")), resultNotes: empty(val(fd,"resultNotes")) }; const r = id ? await realEstateLabItemAdapter.update(supabase, accountId, id, input) : await realEstateLabItemAdapter.create(supabase, accountId, input); revalidatePath(path(account)); return r.ok ? { ok:true, message:"Item salvo." } : { ok:false, error:r.error }; } catch(e){ return { ok:false, error:e instanceof Error ? e.message : "Erro ao salvar item."}; } }
export async function setItemStatusAction(account: string, fd: FormData) { const accountId = await gate(account, true); const supabase = await createClient(); await realEstateLabItemAdapter.changeStatus(supabase, accountId, val(fd,"id") ?? "", val(fd,"status") ?? ""); revalidatePath(path(account)); }
export async function deleteItemAction(account: string, fd: FormData) { const accountId = await gate(account, true, true); const supabase = await createClient(); await realEstateLabItemAdapter.delete(supabase, accountId, val(fd,"id") ?? ""); revalidatePath(path(account)); }
